"""
test
DAG auto-generated by Astro Build.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="cell_1")
def cell_1_func():
    # Write your code here...
    print("THIS IS THE CLOUD IDE")

@dag(
    schedule_interval=None,
    start_date=pendulum.from_format("2022-11-01", "YYYY-MM-DD"),
)
def test():
    cell_1 = cell_1_func()

dag_obj = test()
